---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  # namespace: <nome-aluno>
type: Opaque
data:
  username: ZGV2b3Bz
  password: ZGV2b3BzcGFzcw==

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  # namespace: <nome-aluno>
spec:
  containers:
    - name: mypod
      image: redis
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
